name: todo_list_cubit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  supabase_flutter: ^1.10.25
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  uuid: ^4.2.1
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
